# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6a2006aa6f3d970312d74af21db7e125da1a16e435b856c848c28e0a105e977360c939a054f00b33343329e8079827b8be71f29742429cb99b18f6c5759d3cc

test:
  secret_key_base: 798d940f64e32eca453b6d6ae366d51abacacf63691463fc7da9e72167cde7ab098be6b814b665c05d1d75668bf8c348ff52c3aa3c753d769a53bf87a0037a77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
